name: CI pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: 
          repository: 'ShenLongVansh/portfolio'
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install Node Dependencies
        run: npm Install
      - name: Runs Development Server
        run: npm run dev